const awardeeData = [
  {
    "No": 1,
    "namaLengkap": "Salsabila Tyas Azzahra",
    "noInduk": "P23050009",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Indonesia",
    "fakultas": "MIPA",
    "jurusan": "Geologi",
    "email": "salsabila.tyas@ui.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "26/11/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 2,
    "namaLengkap": "Alifia Zahira Rizky",
    "noInduk": "P23050014",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "IPB University",
    "fakultas": "Sekolah Bisnis",
    "jurusan": "Bisnis",
    "email": "alifiazahirarizky@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "3/6/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 3,
    "namaLengkap": "Arnelia Rimarta Kusuma",
    "noInduk": "P23050015",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "IPB University",
    "fakultas": "Bisnis",
    "jurusan": "Sekolah Bisnis",
    "email": "arnel4yt@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "4/5/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 4,
    "namaLengkap": "Fahmi Athallah Rahmat",
    "noInduk": "P23050017",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "IPB University",
    "fakultas": "Sekolah Bisnis",
    "jurusan": "Bisnis",
    "email": "fahmiathallah@apps.ipb.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "23/03/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 5,
    "namaLengkap": "Yoga Dwi Aprilianto",
    "noInduk": "P23050023",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "IPB University",
    "fakultas": "Sekolah Bisnis",
    "jurusan": "Bisnis",
    "email": "punyayoga@apps.ipb.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "11/4/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 6,
    "namaLengkap": "Dinia Athaya Salsabila",
    "noInduk": "P23060024",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Fakultas Pertanian",
    "jurusan": "Agribisnis",
    "email": "dinia.athaya@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "18/01/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 7,
    "namaLengkap": "Elfira Annisa Sastra",
    "noInduk": "P23060025",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Administrasi Bisnis",
    "email": "elfiraasastra@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "7/9/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 8,
    "namaLengkap": "Jihan Hanifah Sony",
    "noInduk": "P23060027",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Administrasi Bisnis",
    "email": "jihanhanifah001@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "3/5/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 9,
    "namaLengkap": "Sherly Rizki Ardiansyah",
    "noInduk": "P23060030",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Administrasi Bisnis",
    "email": "sherlyardiansyah24@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "24/07/2002",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 10,
    "namaLengkap": "Talitha Almira",
    "noInduk": "P23060032",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Fakultas Pertanian",
    "jurusan": "Agribisnis",
    "email": "talitha21005@mail.unpad.ac.id",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "12/12/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 11,
    "namaLengkap": "Ukasyah Rianza Alfarizi",
    "noInduk": "P23080067",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Creabiz",
    "jurusan": "Studi Pembangunan",
    "email": "ukasyahrianzaalfarizi@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "21/02/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 12,
    "namaLengkap": "Jeni Amelia Putri",
    "noInduk": "P23080073",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Agribisnis",
    "email": "ameliajeni258@student.ub.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "2/6/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 13,
    "namaLengkap": "Ikhwansyah Hanifa",
    "noInduk": "P23100097",
    "kelompok": "FPB1",
    "namaFasilitator": "Zalfa Luqyana Nabilah",
    "universitas": "Universitas Hasanuddin",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Agribisnis",
    "email": "ciwanggong@gmail.com",
    "ro": "Makassar",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "20/03/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 1,
    "namaLengkap": "Alvito Rafif Pangestu",
    "noInduk": "P23050001",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi",
    "email": "alvitorafif.03@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "3/8/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 2,
    "namaLengkap": "Fadhil Hardiansyah",
    "noInduk": "P23050004",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi",
    "email": "fadhilhardiansyah10@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "10/5/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 3,
    "namaLengkap": "Shofiatul Hilwa",
    "noInduk": "P23050010",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi Islam",
    "email": "shofiatulhilwa.xiips3@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "31/03/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 4,
    "namaLengkap": "M. Zidhan",
    "noInduk": "P23050019",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "IPB University",
    "fakultas": "Ekonomi dan Manajemen",
    "jurusan": "Ekonomi Pembangunan",
    "email": "mhdzidhan@apps.ipb.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "27/03/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 5,
    "namaLengkap": "Rafli Ananta Zikri",
    "noInduk": "P23050021",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "IPB University",
    "fakultas": "Ekonomi dan Manajemen",
    "jurusan": "Ilmu Ekonomi Syariah",
    "email": "raflizikr0510@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "5/10/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 6,
    "namaLengkap": "Sindi Novia Anggraeni",
    "noInduk": "P23050022",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "IPB University",
    "fakultas": "Ekonomi dan Manajemen",
    "jurusan": "Ekonomi Sumberdaya dan Lingkungan",
    "email": "sindinovia@apps.ipb.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "15/11/2023",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 7,
    "namaLengkap": "Nailah Rohadatul'Aisy",
    "noInduk": "P23060028",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi",
    "email": "nailahrhdtl@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "9/3/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 8,
    "namaLengkap": "Tarishah Putri Arini",
    "noInduk": "P23060033",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "tarishah21001@mail.unpad.ac.id",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "21/09/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 9,
    "namaLengkap": "Leony Nasywa Devita",
    "noInduk": "P23070054",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "defitaleony@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "24/12/2002",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 10,
    "namaLengkap": "Rayhan Sutan Bahari",
    "noInduk": "P23070057",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "rayhansutan1@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "29/04/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 11,
    "namaLengkap": "Albar Muhammad Aziz",
    "noInduk": "P23080082",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "albarmuhammadaziz98@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "7/3/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 12,
    "namaLengkap": "Muhammad Ghufron Ariawan",
    "noInduk": "P23080089",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "aryaya5671@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "17/04/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 13,
    "namaLengkap": "Rifan Prasetio",
    "noInduk": "P23080092",
    "kelompok": "FPB2",
    "namaFasilitator": "Mohammad Aksyar",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "rifanprasetio02@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "27/02/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 1,
    "namaLengkap": "Hani Oktarini Hizelia",
    "noInduk": "P23050005",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Indonesia",
    "fakultas": "Psikologi",
    "jurusan": "Psikologi",
    "email": "hani.oktarini@ui.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "22/10/2001",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 2,
    "namaLengkap": "Muhamad Rizky Rizqita",
    "noInduk": "P23050007",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Manajemen",
    "email": "muhamad.rizky13@ui.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "17/09/2001",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 3,
    "namaLengkap": "Ananda Mulia Putri Maharani",
    "noInduk": "P23070039",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Hukum",
    "jurusan": "Hukum",
    "email": "ananda.mulia.putri.maharani@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "27/11/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 4,
    "namaLengkap": "Lintang Atha Zahfirah Pramana",
    "noInduk": "P23070041",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Hukum",
    "jurusan": "Hukum",
    "email": "pramanaatha@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "11/11/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 5,
    "namaLengkap": "Namaskara Tawang Kusuma",
    "noInduk": "P23070045",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Psikologi",
    "jurusan": "Psikologi",
    "email": "namaskara.tawang.kusuma@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "24/07/2001",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 6,
    "namaLengkap": "Ahmad Faqih",
    "noInduk": "P23070048",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Manajemen",
    "email": "faqih3358@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "3/2/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 7,
    "namaLengkap": "Dhian Putri Maharani",
    "noInduk": "P23070052",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Hukum",
    "jurusan": "Hukum",
    "email": "dhianputrimaharani08@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "8/9/2023",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 8,
    "namaLengkap": "Khairunnisa Rizki Amila",
    "noInduk": "P23070053",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Manajemen",
    "email": "nisaarzka@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "13/04/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 9,
    "namaLengkap": "Muhammad Irfan Nugraha",
    "noInduk": "P23070055",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Akuntansi",
    "email": "irfan.nugraha9999@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "17/07/2002",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 10,
    "namaLengkap": "Irfan Adzan Maulana",
    "noInduk": "P23080072",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Manajemen",
    "email": "irfanadzanm2702@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "27/02/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 11,
    "namaLengkap": "Firstanti Bunga Rahma",
    "noInduk": "P23080084",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Akuntansi",
    "email": "firstanti.bunga.rahma-2021@feb.unair.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "14/08/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 12,
    "namaLengkap": "Nina Dzurotul Mahmudah",
    "noInduk": "P23080091",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Akuntansi",
    "email": "ninadzurotul711@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "7/11/2001",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 13,
    "namaLengkap": "Zafirah Amaani",
    "noInduk": "P23080094",
    "kelompok": "FPB3",
    "namaFasilitator": "Salmaa Ramadhani",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Akuntansi",
    "email": "firaamaani462@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "4/6/2002",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 1,
    "namaLengkap": "Daffa Pratama",
    "noInduk": "P23050002",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Indonesia",
    "fakultas": "Hukum",
    "jurusan": "Ilmu Hukum",
    "email": "daffa.pratama11@ui.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "2/12/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 2,
    "namaLengkap": "Rofy Candra Rusdiana",
    "noInduk": "P23050008",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Indonesia",
    "fakultas": "Hukum",
    "jurusan": "Ilmu Hukum",
    "email": "rofy.candra@ui.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "22/03/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 3,
    "namaLengkap": "Dhea Fadhila Salsabila",
    "noInduk": "P23050016",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "IPB University",
    "fakultas": "Matematika dan Ilmu Pengetahuan Alam",
    "jurusan": "Aktuaria",
    "email": "dheafadhilaslsbl@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "7/4/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 4,
    "namaLengkap": "Teguh Irdhansyah",
    "noInduk": "P23060034",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Padjajaran",
    "fakultas": "MIPA",
    "jurusan": "Statistika",
    "email": "teguhirdhansyah9@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "25/04/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 5,
    "namaLengkap": "Alfahri Rifki Fahrezi",
    "noInduk": "P23070038",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "MIPA",
    "jurusan": "Elektronika dan Instrumentasi",
    "email": "alfahri.rifki2103@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "21/03/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 6,
    "namaLengkap": "Bilqis Hafsah Ababiel",
    "noInduk": "P23070040",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "MIPA",
    "jurusan": "Elektronika dan Instrumentasi",
    "email": "bilqis.hafsah.02@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "21/10/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 7,
    "namaLengkap": "Nadia Hasna Azzahra",
    "noInduk": "P23070044",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "MIPA",
    "jurusan": "Ilmu Komputer",
    "email": "nadia.hasna.azzahra@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "17/04/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 8,
    "namaLengkap": "Amelia Zulfa Farida",
    "noInduk": "P23070051",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Sains dan Matematika",
    "jurusan": "Statistika",
    "email": "ameliazoelfafarida@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "2/9/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 9,
    "namaLengkap": "Anugrah Sri Wahyuni",
    "noInduk": "P23080059",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Electics",
    "jurusan": "Teknik Elektro",
    "email": "sriwahyunianugrah@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "8/11/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 10,
    "namaLengkap": "Muhammad Daffa Ashdaqfillah",
    "noInduk": "P23080062",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Electics",
    "jurusan": "Teknik Informatika",
    "email": "muhdaffa2410@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "24/10/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 11,
    "namaLengkap": "Ocha Oxana Octavia",
    "noInduk": "P23080063",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Scientics",
    "jurusan": "Teknik Kelautan",
    "email": "ocha.oxanao@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "13/10/2002",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 12,
    "namaLengkap": "Anindya Yustika",
    "noInduk": "P23080071",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Hukum",
    "jurusan": "Ilmu Hukum",
    "email": "anindyayustika@student.ub.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "24/05/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 13,
    "namaLengkap": "Michael Rahadiyan Wijaya",
    "noInduk": "P23080076",
    "kelompok": "FPB4",
    "namaFasilitator": "Rahmat Haqqi Utama",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Sistem Informasi",
    "email": "michael.rwi03@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2021,
    "semester": 7,
    "tanggalLahir": "11/6/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 1,
    "namaLengkap": "Zuhdy Nadhif Ayyasy",
    "noInduk": "P23050012",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Ilmu Komputer",
    "email": "zuhdy.nadhif.ayyasy@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "1/6/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 2,
    "namaLengkap": "Ikhwan Al Hakim",
    "noInduk": "P23060036",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Institut Teknologi Bandung",
    "fakultas": "Sekolah Teknik Elektro dan Informatika",
    "jurusan": "Teknik Informatika",
    "email": "13522147@std.stei.itb.ac.id",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "24/08/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 3,
    "namaLengkap": "Aisyah Putri Khurinin",
    "noInduk": "P23070037",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "MIPA",
    "jurusan": "Ilmu Komputer",
    "email": "aisyahputrikhurinin@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "2/10/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 4,
    "namaLengkap": "Aria Nalini",
    "noInduk": "P23080060",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Electics",
    "jurusan": "Teknik Informatika",
    "email": "naliniaria4@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "10/11/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 5,
    "namaLengkap": "Rafhi Sadipta",
    "noInduk": "P23080064",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Electics",
    "jurusan": "Teknik Informatika",
    "email": "rafhisadipta@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "9/7/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 6,
    "namaLengkap": "Abdullah Hilal Adi Sumarno",
    "noInduk": "P23080068",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Teknik Informatika",
    "email": "abdullahhilal2021@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "23/06/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 7,
    "namaLengkap": "Ahmad Zaki",
    "noInduk": "P23080069",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Teknik Informatika",
    "email": "jackystorm8@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "28/02/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 8,
    "namaLengkap": "Anindya Candrakanti Yusnida",
    "noInduk": "P23080070",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Sistem Informasi",
    "email": "acandrakanti@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "28/01/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 9,
    "namaLengkap": "Kartika Putri Dewa Yani",
    "noInduk": "P23080074",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Sistem Informasi",
    "email": "kartikapdy@student.ub.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "24/12/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 10,
    "namaLengkap": "Kurnita Ruci Widyana",
    "noInduk": "P23080075",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Teknik Komputer",
    "email": "kurnitaruci@student.ub.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "8/6/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 11,
    "namaLengkap": "Nimah Shafwah Addini",
    "noInduk": "P23080078",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Sistem Informasi",
    "email": "nimahaddin@student.ub.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "13/07/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 12,
    "namaLengkap": "Rania Jilan",
    "noInduk": "P23080079",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ilmu Komputer",
    "jurusan": "Teknologi Informasi",
    "email": "ranihany223@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "2/9/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 13,
    "namaLengkap": "Memoreza Sabana",
    "noInduk": "P23080087",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Airlangga",
    "fakultas": "Sains Dan Teknologi",
    "jurusan": "Sistem Informasi",
    "email": "memorezasa@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "16/10/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 14,
    "namaLengkap": "Mochammad Fahd Ali Hillaby",
    "noInduk": "P23080088",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Airlangga",
    "fakultas": "Teknologi Maju dan Multidisiplin",
    "jurusan": "Teknologi Sains Data",
    "email": "mochammad.fahd.ali-2022@ftmm.unair.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "27/11/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 15,
    "namaLengkap": "Zain Zaidan Abduh",
    "noInduk": "P23080095",
    "kelompok": "FPB5",
    "namaFasilitator": "Nafkhatul Wahidah, M.Psi.,Psikolog",
    "universitas": "Universitas Airlangga",
    "fakultas": "Sains Dan Teknologi",
    "jurusan": "Sistem Informasi",
    "email": "zain.zaidan.abduh-2022@fst.unair.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "6/11/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 1,
    "namaLengkap": "Fabian Rusmeinka Pane",
    "noInduk": "P23050003",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi Islam",
    "email": "fabianrpane@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "20/12/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 2,
    "namaLengkap": "Teuku Muhammad Nazhif Syauqi",
    "noInduk": "P23050011",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Indonesia",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Bisnis Islam",
    "email": "nazhifsyauqikuliah@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "14/10/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 3,
    "namaLengkap": "Alban Odidante Dudon",
    "noInduk": "P23050013",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "IPB University",
    "fakultas": "Ekonomi dan Manajemen",
    "jurusan": "Ilmu Ekonomi Syariah",
    "email": "albanodgtg@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "14/08/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 4,
    "namaLengkap": "Fayyadh Ahmad Fauzan",
    "noInduk": "P23050018",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "IPB University",
    "fakultas": "Sekolah Bisnis",
    "jurusan": "Bisnis",
    "email": "fayyadh.fauzan@apps.ipb.ac.id",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "9/2/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 5,
    "namaLengkap": "Muhammad Fikri Aulia Amrullah",
    "noInduk": "P23050020",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "IPB University",
    "fakultas": "Ekonomi dan Manajemen",
    "jurusan": "Ekonomi Syariah",
    "email": "fikriauliaamrullah@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "6/7/2002",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 6,
    "namaLengkap": "Mohammad Agta Annafi Sugiyantoro",
    "noInduk": "P23070042",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi",
    "email": "mohammadagtaannafisugiyantoro2003@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "31/05/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 7,
    "namaLengkap": "Muhammad Naufal Chaidar",
    "noInduk": "P23070043",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Pembangunan Ekonomi Kewilayahan",
    "email": "naufalchaidar8@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "3/9/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 8,
    "namaLengkap": "Alfinda Dwi",
    "noInduk": "P23070049",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Ekonomi islam",
    "email": "alfindadwieqselinta@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "30/12/2003",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 9,
    "namaLengkap": "Paramita Hedyningtyas",
    "noInduk": "P23070056",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Ekonomika dan Bisnis",
    "jurusan": "Akuntansi Perpajakan",
    "email": "paramitatys@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "26/06/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 10,
    "namaLengkap": "Muhammad Fazil Zihni",
    "noInduk": "P23080077",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi",
    "email": "fazilzihni217@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "29/10/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 11,
    "namaLengkap": "Maulana Achmad Shovyanhadi Al Farisi",
    "noInduk": "P23080086",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ekonomi Islam",
    "email": "maulana.ach.ovyanhadi-2022@feb.unair.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "20/11/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 12,
    "namaLengkap": "Dian Resky Auliyah Amin",
    "noInduk": "P23100096",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Hasanuddin",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Akuntansi",
    "email": "dianreskyauliyah23@gmail.com",
    "ro": "Makassar",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "23/08/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 13,
    "namaLengkap": "Muh. Syafa'At Ashan",
    "noInduk": "P23100098",
    "kelompok": "FPB6",
    "namaFasilitator": "Sukma Hanifani",
    "universitas": "Universitas Hasanuddin",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Ilmu Ekonomi",
    "email": "kiflyr@gmail.com",
    "ro": "Makassar",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "20/03/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 1,
    "namaLengkap": "Hanum Hasanah",
    "noInduk": "P23050006",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Indonesia",
    "fakultas": "Psikologi",
    "jurusan": "Psikologi",
    "email": "hanumhasanah23@gmail.com",
    "ro": "Jakarta",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "23/06/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 2,
    "namaLengkap": "Jaihan Hanifah Isa",
    "noInduk": "P23060026",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Hukum",
    "jurusan": "Ilmu Hukum",
    "email": "jaihanhanifah675@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "20/09/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 3,
    "namaLengkap": "Najwa Amalia Mansoor",
    "noInduk": "P23060029",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Manajemen",
    "email": "najwaamalia875@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "28/05/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 4,
    "namaLengkap": "Syamil Akbar Alghifari",
    "noInduk": "P23060031",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Padjajaran",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Manajemen",
    "email": "syamilakbar.edu@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "1/6/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 5,
    "namaLengkap": "Sabrina Arum Cahya",
    "noInduk": "P23070046",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Psikologi",
    "jurusan": "Psikologi",
    "email": "sabrinaarumcahya@mail.ugm.ac.id",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "10/10/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 6,
    "namaLengkap": "Umar Abdul Aziz Susilo Rahmat Wibowo",
    "noInduk": "P23070047",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Gadjah Mada",
    "fakultas": "Psikologi",
    "jurusan": "Psikologi",
    "email": "srwumar@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "20/08/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 7,
    "namaLengkap": "Anis Aufar Makarim",
    "noInduk": "P23080058",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Creabiz",
    "jurusan": "Manajemen Bisnis",
    "email": "nsaufar@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "6/8/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 8,
    "namaLengkap": "Shahrul Hazni",
    "noInduk": "P23080080",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Brawijaya",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Manajemen",
    "email": "shahrulhazni0905@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "9/5/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 9,
    "namaLengkap": "Aci",
    "noInduk": "P23080081",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Airlangga",
    "fakultas": "Hukum",
    "jurusan": "Ilmu Hukum",
    "email": "cicia832@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "11/6/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 10,
    "namaLengkap": "Azra Yahya",
    "noInduk": "P23080083",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "MANAJEMEN",
    "email": "azrasmala@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "15/06/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 11,
    "namaLengkap": "Keshia Larasati",
    "noInduk": "P23080085",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Airlangga",
    "fakultas": "Psikologi",
    "jurusan": "Psikologi",
    "email": "keshia.larasati-2022@psikologi.unair.ac.id",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "4/8/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 12,
    "namaLengkap": "Syarifa Aulia Puteri",
    "noInduk": "P23080093",
    "kelompok": "FPB7",
    "namaFasilitator": "Rachmadhiya Salsabila",
    "universitas": "Universitas Airlangga",
    "fakultas": "Ekonomi dan Bisnis",
    "jurusan": "Manajemen",
    "email": "syarifauliap@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "22/05/2004",
    "kelasLiterasiEkonomi": "A"
  },
  {
    "No": 1,
    "namaLengkap": "Hanief Azmi",
    "noInduk": "P23060035",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Institut Teknologi Bandung",
    "fakultas": "MIPA",
    "jurusan": "Fisika",
    "email": "haniefazmir@gmail.com",
    "ro": "Bandung",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "3/7/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 2,
    "namaLengkap": "Alya Putri Meyriska",
    "noInduk": "P23070050",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Universitas Diponegoro",
    "fakultas": "Sains dan Matematika",
    "jurusan": "Matemtika",
    "email": "alyaputri020504@gmail.com",
    "ro": "Semarang",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "2/5/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 3,
    "namaLengkap": "Calia Jahidatul I",
    "noInduk": "P23080061",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Electics",
    "jurusan": "Teknik Biomedik",
    "email": "caliajahidatulizzah22@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "22/12/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 4,
    "namaLengkap": "Rafi Adyatma Ramadhan",
    "noInduk": "P23080065",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Scientics",
    "jurusan": "Aktuaria",
    "email": "rafi.adyatmaa7@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "20/11/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 5,
    "namaLengkap": "Shofi Luthfiyah Aryanti",
    "noInduk": "P23080066",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Institut Teknologi Sepuluh Nopember",
    "fakultas": "Scientics",
    "jurusan": "Aktuaria",
    "email": "shofiluthfiyah15@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "15/12/2003",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 6,
    "namaLengkap": "Nadelia Lufita Pramistya",
    "noInduk": "P23080090",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Universitas Airlangga",
    "fakultas": "Hukum",
    "jurusan": "Ilmu  Hukum",
    "email": "adellufita@gmail.com",
    "ro": "Surabaya",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "6/1/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 7,
    "namaLengkap": "Muhammad Ali Islam Bahmi",
    "noInduk": "P23100099",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Universitas Hasanuddin",
    "fakultas": "Hukum",
    "jurusan": "Ilmu Hukum",
    "email": "aliislambm0907@gmail.com",
    "ro": "Makassar",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "7/9/2004",
    "kelasLiterasiEkonomi": "B"
  },
  {
    "No": 8,
    "namaLengkap": "Sahrul",
    "noInduk": "P23100100",
    "kelompok": "FPB8",
    "namaFasilitator": "Ridzky Berliana Kusuma",
    "universitas": "Universitas Hasanuddin",
    "fakultas": "MIPA",
    "jurusan": "Geofisika",
    "email": "sahrul22h@student.unhas.ac.id",
    "ro": "Makassar",
    "angkatanMasukKuliah": 2022,
    "semester": 5,
    "tanggalLahir": "29/08/2004",
    "kelasLiterasiEkonomi": "B"
  }
]

module.exports = awardeeData;